gdamore/tcell

- mkdatabase.sh
Not everyone has ksh, but everyone has dash or bash symlinked to sh.
> mkdatabase.sh: Use sh instead of ksh

- key.go
This map of variables might be useful to applications wanting to convert text to keys, e.g. for key bindings.
> Make keyNames variable public

- color.go
This patch makes `ColorNames` and `ColorValues` public, and adds documentation. I am unsure about the origin of the names, maybe someone else can shed some light on this?
The variables can be useful when implementing help screens or tab completion in programs which have configurable colors.
> Document and publish color names and RGB values.

- views/boxlayout.go
- Widget might be using not just View but other mechanisms for rendering
aware of the view size (e.g. `ViewPort`).
- By using the view reference out of the `Widget`, `Widget` doesn't have a
chance to react on this layout algorithm
- That's an existing bug that happens when we try to use `CellView` inside
of an `BoxLayout`
> Adding Widget Resize to BoxLayout function

- console_win.go
Closes #158. Also ought to solve rprichard/winpty#119 and junegunn/fzf#962, and maybe some other issues too.
> Fix cScreen.Fini() race condition (#158)

- tscreen.go
- tscreen_bsd.go
- tscreen_linux.go
- tscreen_posix.go
fixes #164 KeyEscape does not work in Go 1.9 under Linux
This is a complete refactor of the input loop for UNIX systems.
We use a blocking reader on the TTY, and a separate select
loop for timers and other events.  This means that our idle
use should be low now.
> fixes #129 Very high IDLE_WAKE - Power consumption

- terminfo/mkinfo.go
- terminfo/term_screen.go
- terminfo/term_screen_256color.go
I noticed that when running a tcell application under tmux using
TERM=screen-256color, some text rendered with style attributes
like bold and underline appeared preceded with "17". This seemed
to come from tcell sending "AttrOff"/sgr0, which in
term_screen_256color.go looks like:
AttrOff:      "\x1b[m\x0017"
infocmp screen-256color expresses sgr0 like this:
sgr0=\E[m\017
This terminfo man page implies that \017 should be interpreted as
the octal representation of 15 decimal.
https://www.mkssoftware.com/docs/man5/terminfo.5.asp
The terminfo generator mkinfo.go parses the \0 as a zero, then
the following 17 as the digits 1 and 7. This patch modifies
mkinfo.go and results in the following instead
AttrOff:      "\x1b[m\x0f"
This seems to clear up the "17" problem for me. But I am not a …
> Parse terminfo values containing numbers expressed in octal syntax.

- simulation.go
So that it's possible to write a test using less than an `80x25` screen.
> Fix simscreen.SetSize

- views/app.go
Fixes app screen reset, so that it resets when `panic()`ing.
> Defer screen finish in app run

- terminfo/terminfo.go
On Windows 10, LookupTerminfo(name string) in terminfo.go was getting passed an empty string, then crashing on name[0] being out of bounds.
> fix #172, don't crash on empty name string on call to LookupTerminfo

- tscreen.go
I've been experiencing  panics occasionally/randomly on this `close(t.quit)` for double closes.
The changes seem to fix some of the obscure panics.
> Fix panic when quit chan is double closed

- tscreen.go
Setting t.quit to nil while the mainLoop is running causes a race condition when the Fini() method is called. This change instead never sets the `t.quit` channel to nil, instead using a select expression with a default to guard against closing the channel twice.
Original `-race` output:
```
==================
WARNING: DATA RACE
Write at 0x00c420426218 by goroutine 23:
github.com/gdamore/tcell.(*tScreen).Fini()
/Users/tylersommer/go/src/github.com/gdamore/tcell/tscreen.go:403 +0x322
github.com/rivo/tview.(*Application).Stop()
/Users/tylersommer/go/src/github.com/rivo/tview/application.go:179 +0xb2
github.com/rivo/tview.(*Application).Run()
/Users/tylersommer/go/src/github.com/rivo/tview/application.go:148 +0x4a3
github.com/motki/cli/command.InventoryV2Command.Handle() …
```
> Fix data race in tScreen shutdown

- simulation.go
This pull request fixes SimulationScreen to ensure that PollEvent returns nil when simscreen#Fini is called.
> Initialize quit chan of simscreen so that PollEvent returns nil when Fini called

- console_win.go
As discussed in issue #182, no mouse events can be accepted as long as the console is in QuickEdit mode. According to the documentation of SetConsoleMode, the Quick Edit mode can be deactivated if the flag ENABLE_EXTENDED_FLAGS is passed without the flag ENABLE_QUICK_EDIT_MODE.
See the explanation of the flag ENABLE_QUICK_EDIT_MODE in the documentation:
https://docs.microsoft.com/en-us/windows/console/setconsolemode
> disable QuickEdit Mode on EnableMouse() in Win10

- terminfo/mkinfo.go
Auto detect the base as implied by `0` or `0x` prefixes.
Fixes #212
> Allow octal and hexadecimal conversion to int

- console_win.go
This Pull-Request is a modification of this issue: https://github.com/gdamore/tcell/issues/250
When content is full-width character, this following `width` is `2`.
https://github.com/gdamore/tcell/blob/master/console_win.go#L758
But, `SetDirty` method is called only at the beginning.
So, I have modified it to call `SetDirty` method at the back place of full-width characters.
> Call SetDirty method on the back place of full-width characters.

- terminfo/terminfo.go
- tscreen.go
I've noticed that my tcell applications can be quite slow updating the screen
over an ssh connection, especially compared to frameworks like
urwid. Debugging with strace showed that each cell was written to the terminal
interleaved with calls to epoll_pwait() e.g. here rendering two bytes, chosen
randomly from my strace capture:
9874  22:56:10.508632 write(5, "f", 1)  = 1
9871  22:56:10.508654 <... epoll_pwait resumed> [{EPOLLOUT, {u32=754322992, u64=139801939807792}}, {EPOLLOUT, {u32=754323200, u64=139801939808000}}], 128, -1, NULL, 3) = 2
9871  22:56:10.508674 epoll_pwait(4,  <unfinished ...>
9874  22:56:10.508806 write(5, " ", 1 <unfinished ...>
9871  22:56:10.508820 <... epoll_pwait resumed> [{EPOLLOUT, {u32=754322992, u64=139801939807792}}, {EPOLLOUT, {u32=754323200, …
> An attempt to speed up tcell screen rendering.

- go.mod
- go.sum
Hi - I tried to update my work to use your latest version of tcell using the command below, and ran into a grungy go modules error. It looks like the go-colorful repo has fixed their references to go-sqlmock with this commit: https://github.com/lucasb-eyer/go-colorful/commit/4de7d682992e4105e105acd8ec5deb03a5bc542a. In my fork of tcell, updating go-colorful with 
$ go get -u github.com/lucasb-eyer/go-colorful
seemed to resolve the issue.
Graham
$ go get -u -v github.com/gdamore/tcell
Fetching https://golang.org/x/text?go-get=1
Fetching https://gopkg.in/DATA-DOG/go-sqlmock.v1?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", …
> An attempt to work around a gopkg.in/module error in a dependency.

- go.mod
- go.sum
go-sqlmock, which is a dependency for go-colorful tests, have switched from
gopkg.in to Go modules. This repository still records the old gopkg.in import
path in the go.mod file, which confuses `go mod`:
go: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.3: go.mod has non-....v1 module path "github.com/DATA-DOG/go-sqlmock" at revision v1.3.3
This commit updates the go.mod file to use the new import path.
Can you release a new minor version after this is merged, so that we can use this library without hitting errors? Thanks!
> Update go-colorful dependency

- tscreen.go
I humbly submit this patch as another attempt to address the issue that tcell
will only paste up to 11 characters at a time. The problem is caused by the
fact that events (key, mouse, etc) constructed from the stream of raw input
characters are sent to the consuming application over a length-10 channel via
screen.PostEvent() which, if the channel is full, will drop what can't be sent
immediately. If the input stream grows rapidly e.g. because the user pasted a
large section of text into the running tcell application, then more than 10
events will likely be built from the chunk of input read by scanInput().
A blocking channel send is not used (i.e. PostEventWait() instead of
PostEvent()) because the channel send is issued from a call stack in which the
screen struct's lock is held. If the …
> Another attempt to fix limited length of paste.

- console_win.go
A gowid user reported that mouse movement in their gowid(tcell) application
was causing the console cursor to flicker on windows, jumping from the current
position in the console to the top left corner, and back again. In part, this
is an artifact of the way I render a gowid "canvas" - calling HideCursor()
unilaterally, then calling ShowCursor(x, y) if the canvas contains a logical
cursor that is within bounds. Because currently every mouse event causes a
gowid application redraw, on windows the effect is to cause the cursor to jump
to the top left briefly, disappear, then reappear in the previous
position. You can see it most easily by moving the mouse rapidly left and
right.
An upstream fix is for me to only call HideCursor() if I know I'm not going to
call ShowCursor(x, y). But the …
> On windows, don't change cursor position if about to hide cursor.

- terminfo/dynamic/dynamic.go
- tscreen.go
fixes #285 Loss of color/mangled formatting on GNU screen
fixes #93 use the terminfo database instead of the json database
This change falls back to using a dynamically generated terminal
description (using infocmp, which must be on the path) if the builtin
database doesn't have a suitable description.
For most users this should resolve the problem of unknown terminals.
> fixes #279 process new terminal descriptions at application runtime

- go.mod
- go.sum
- tscreen_linux.go
- tscreen_posix.go
This change has refactored the illumos layer to make use of the
golang.org/x/sys/unix package to achieve a clean cgo-free solution
for illumos and Solaris.
The approach here should be a template for other systems.  I've
also made some changes to the Linux port.
> fixes #257 Broken illumos Support

- terms_default.go
- terms_dynamic.go
- terms_static.go
- tscreen.go
This makes the default build about 150k larger, but includes all
the good terminals needed to make most folks happy.  In addition,
it allows a build tag of tcell_minimal to suppress that.  Finally,
we do not include infocmp support on platforms unlikely to support
it, such as Windows, nacl, android, etc.
> fixes #302 merge extended terminfo definitions into default

- go.mod
- go.sum
I submitted [PR #39](https://github.com/lucasb-eyer/go-colorful/pull/39) on `lucasb-eyer/go-colorful` that avoids it pulling in the unnecessary `go-sqlmock` dependency. This is a PR on tcell to update to that version of `go-colorful` to avoid the (indirect) dependency for tcell.
> Update go-colorful to v1.0.3 to avoid go-sqlmock dependency

- go.mod
- go.sum
This upgrade fixes issues with rendering certain "CP437" chars -- see https://github.com/mattn/go-runewidth/issues/34
> Update runewidth to v0.0.7 to fix char width issues

- terminfo/dynamic/dynamic.go
- terminfo/mkinfo.go
@klamonte opened this issue against gowid, a package that relies on tcell for
all its terminal handling: https://github.com/gcla/gowid/issues/24. It
describes how a shell inside a terminal widget that the TUI launches freezes
when the user hits backspace. The TUI loads a tcell TermInfo struct for the
screen-256color terminal and that struct codes KeyBackspace as the single byte
0xff - and so the byte 0xff was sent to the tty. On my Ubuntu 19.04 machine,
`infocmp screen-256color` shows `kbs` is `^?` According to
https://en.wikipedia.org/wiki/Caret_notation, `^?` should map to 0x7f (127) -
"The digraph stands for the control character whose ASCII code is the same as
the character's ASCII code with the uppermost bit, in a 7-bit encoding,
reversed". This affects both mkinfo.go, the generator …
> Fix control-character encoding for non-alphabet characters

- tscreen_linux.go
Sometimes, the TIOCGWINSZ ioctl returns all zeroes (including columns,
rows) without an error. I found this when experimenting with the jexer
TUI toolkit for java e.g.
mvn dependency:get -Dartifact=com.gitlab.klamonte:jexer:0.3.2
jexer -jar ~/.m2/repository/com/gitlab/klamonte/jexer/0.3.2/jexer-0.3.2.jar
Once the demo starts, click the "Terminal" button, then type
stty size
it returns
0 0
My understanding is that this is normal, and happens until SIGWINCH is
received, or the size is set explicitly with TIOCSWINSZ.
My tcell application crashed under the jexer terminal because I didn't
anticipate a window size of (0,0).
If you run vim under the jexer terminal, it correctly sizes itself to
80x24. The shell's TERM variable is xterm, and infocmp xterm | grep cols
shows a default of 80 and a …
> Provide a fallback terminal size if the OS returns (0,0)

- views/cellarea.go
The PR changes two things:
Removes cursor position keeping from CellView, leaves it to CellModel.
Adds GetModel() method to CellView, so one can build on existing model functions in TextArea for example.
> CellView changes

- views/text.go
- views/text_test.go
Current Text widget behavior tries to compute the longest line length but unfortunately the `length` var wasn't resetting properly causing the total width to be incorrect.
I added a test which was failing before the fix
> Fixed Text widget incorrect width calculation for multiline strings

- _demos/beep.go
- console_win.go
- screen.go
- sim_test.go
- simulation.go
- tscreen_bsd.go
- tscreen_darwin.go
- tscreen_linux.go
- tscreen_stub.go
- tscreen_windows.go
Add a Beep() method to the Screen interface. On *nix systems, this
writes the bell character (0x07) to the tty. On Windows, we call the
MessageBeep syscall.
Fixes: #2
> Implement Beep() API

- tscreen.go
Hello,
This is a simple change that brings a noticeable improvement in memory efficiency, by allocating the buffer to read the input key once, outside the loop, and reuse it instead of allocating on each iteration.
This is a bit tricky to test and benchmark because it is deep in the internals of tScreen, so what I did is run this program:
```
func main() {
s, err := tcell.NewScreen()
if err != nil {
log.Fatal(err)
}
if err := s.Init(); err != nil {
log.Fatal(err)
}
var before, after runtime.MemStats
runtime.ReadMemStats(&before)
defer func() {
runtime.ReadMemStats(&after)
s.Fini()
diff := after.TotalAlloc - before.TotalAlloc
fmt.Printf("\n%d bytes (%dKB) allocated\n", diff, diff/1024)
}()
for ev := s.PollEvent(); ev != nil; ev = s.PollEvent() {
switch ev := ev.(type) {
case …
```
> allocate inputLoop buffer once, outside the loop

- tscreen_solaris.go
The build for the "solaris" and "illumos" tags appears to have been
broken by commit 8ec73b6fa6c543d5d067722c0444b07f7607ba2f, which
introduced the Beep() API.  Restore functionality by using the same
implementation as every other UNIX family platform.
> fix build on illumos after Beep() API

- README.adoc
As mentioned at on its homepage, the project is no longer being maintained and has been archived
> Mark tui-go as deprecated

- views/cellarea.go
Removing SetCursor makes it possible to add lines to the model on the fly, while keeping the cursor in position.
Go also initializes them with 0, no need to set it manually.
I am not perfectly sure about what consequences it could cause.
I have tried to make it panic with the following:
```
ta := views.NewTextArea()
ta.SetContent("One\nTwo\nThree")
ta.EnableCursor(true)
ta.SetCursor(5,3)
ta.SetContent("Boo!")
```
But first cursor movement jumps back to the model. So I think it will not cause regression, but let me know if I should try something else too.
> Remove SetCursor(0,0) from CellArea SetModel

- README.adoc
Tpong is a remake of old-school Pong in terminal with additional features.
> Add tpong to examples list

- _demos/boxes.go
- _demos/mouse.go
- attr.go
- color.go
- color_test.go
- console_win.go
- style.go
- tscreen.go
This causes colors that are set that are low numbered to
be treated as themed colors -- basically honoring the palette
of the terminal.
The Style and Color implementations have changed quite a bit
to permit growth -- the colors are now 64-bits wide to permit
using the upper bits as flags, and to leave room for a future
alpha channel.
There is a new TrueColor() method on colors that obtains the
value as strict RGB value, and this will be used in lieu of
whatever terminal colors are provided -- giving the application
full control over the color space if they want, without
forcibly clobbering user preferences for terminals for the
vast majority of cases.
> fixes #314 Implement `setf` & `setb`

- terminfo/a/alacritty/term.go
For tcell programs on alacritty to be able to display italics.
Source: <https://github.com/alacritty/alacritty/blob/master/extra/alacritty.info#L56>
> Add italic code to alacritty terminfo

- console_win.go
The Windows input scanner does not hold the screen lock, so we can
safely just block if we need to, so we use PostEventWait().
> fixes #319 Pasting on windows still does a maximum of 10 characters

- terminfo/terminfo.go
I noticed this problem while running a gowid test program (palette.go)
with `TERM=xterm-16color`. This terminal type is not present in tcell's
built-in database, and so tcell falls back to the dynamic terminal type
by parsing the output of infocmp. The symptom was that foreground colors
were not correctly set, leaving a monochrome screen. This seems to be
caused by a problem interpreting the *background* color terminfo
rule. The attribute to set background color is defined like this (Ubuntu
20.04):
```
$ infocmp xterm-16color | grep setab
setab=\E[%?%p1%{8}%<%t%p1%'('%+%e%p1%{92}%+%;%dm,
```
The middle sections says `if p1<8 then push(p1+'(')`. `(` is ascii
40. If I run
```
$ tput setab 5
```
the terminal sees `ESC[45m`. This correctly sets the background color to
magenta. But if I tell …
> Change interpretation of pushing quoted character in terminfo parser

- README.adoc
I added a link to https://github.com/Bios-Marcel/memoryalike.
It's a small terminal game written with tcell as it's sole dependency.
> Add Bios-Marcel/memoryalike to the readme

- README.adoc
There was a typo in my previous PR, I didn't notice, sorry
> Fixed typo in example link description

- terminfo/terminfo.go
@tslocum reported that the commit at 2d6d7fbe broke mouse support in
cview (https://github.com/gdamore/tcell/pull/384#issuecomment-698422464). The
purpose of the original commit was to fix a terminfo background color
code parsing problem that I spotted using TERM=xterm-16color:
$ infocmp xterm-16color | grep setab
setab=\E[%?%p1%{8}%<%t%p1%'('%+%e%p1%{92}%+%;%dm,
The middle sections says "if p1<8 then push(p1+'(') ". '(' is ascii
40. The sequence '%d' will then pop from the stack and interpreting the
result as an integer.
My change above was to have tcell assume the sequence between two single
quotes was a single ASCII character e.g. '(' and push that to the
terminfo stack as an integer with the ASCII value of the character
e.g. push(40:int). I didn't find any counterexamples in my local …
> Attempted fix of a regression I introduced - breaking mouse support!

- CHANGESv2.adoc
The import path in CHANGESv2.adoc was wrong and didn't match README.adoc.
This fixes that.
> Fix CHANGESv2.adoc Import Path

- _demos/mouse.go
- console_win.go
- key.go
- paste.go
- screen.go
- simulation.go
- terminfo/dynamic/dynamic.go
- terminfo/terminfo.go
- tscreen.go
This adds Bracketed Paste support for terminals that have mouse
support and support it.  The bracketing events are EventPaste,
with methods to note Start() or End() of the paste.  Content
comes in as normal rune events.  Programs must opt-in to this by
calling screen.EnablePaste().
> fixes #120 Support for bracketed paste mode

- simulation.go
InjectKeyBytes would go into an endless loop for single bytes smaller than a blank.
> Fix endless loop

- README.adoc
Resolves #417  
Add the awesome-gocui's gocui fork to the readme because we now use tcell 🎉
> Add gocui to readme

- _demos/mouse.go
- console_win.go
- nonblock_bsd.go
- nonblock_stub.go
- nonblock_unix.go
- screen.go
- simulation.go
- tscreen.go
- tscreen_unix.go
fixes #194 Starting multiple screen sessions (lost key event)
You can test this by using the mouse demo, which now supports pressing
CTRL-Z.  This does not actually suspend the demo, but starts a subshell
which takes over.  After the subshell is exited, the demo takes control
of the screen back.  This can be done multiple times, and it is possible
to start multiple "nested" iterations of the demo this way.
> Support for new Suspend and Resume API.

- console_win.go
It seems too many unused codes are left in console_win.go, which makes this obvious problem hard to be aware of while coding.
> fixes PollEvent() hung after Fini() on windows

- tscreen.go
- tscreen_unix.go
Suspend call currently exits ca mode. So after the first suspend/resume
the program does not use the alternate screen anymore. Therefore Resume
needs to enter ca mode again.
> switch back to ca mode after suspend/resume

- README.adoc
I published this yesterday on github. It's a tmux plugin that scrapes
the active tmux pane for a magic wormhole code, then downloads and
optionally opens the file tied to the code. I wrote this to make it
easier to get pcaps from termshark into Wireshark. This plugin uses
gowid which itself depends wholly on tcell to manipulate the
terminal. Link: https://github.com/gcla/tmux-wormhole
> Add tmux-wormhole to the list of tcell-dependent apps

- README.adoc
gruid-tcell is a tcell-based driver for the grid-based UI and game
framework gruid. I would be glad to see it added on the examples.
Thanks for making tcell!
> Add gruid-tcell to the list of examples in the README

- README.adoc
Aretext is a minimalist text editor with vim key bindings.
Thanks for all your work on tcell!  This project would not have been possible without it.
> Add aretext to the list of examples in the README

- console_win.go
- event_test.go
- screen.go
- simulation.go
- tscreen.go
This PR proposes an alternative API for getting Events. Version 2. The following method is added:
```go
type Screen interface {
...
// ChannelEvents is an infinite loop that waits for an event and
// channels it into the user provided channel. When Fini() is called
// or quit is closed, the function returns. This function should be
// used as a goroutine.
ChannelEvents(ch chan<- Event, quit <-chan struct{})
...
}
```
Previous version: #461.
> Add Screen.ChannelEvents v2

- screen.go
This adds names to the return values of the `Size` function to add
context. This also changes the return declarations to use the shortcut
when both named return values are the same type, by only specifying the
type once.
***
This is a pretty small change, and only for documentation purposes. I believe that it's easier to read the function declaration than the function's documentation to determine the context of the return values. For me, personally, I look at the function declaration before the comments when reading the docs on pkg.go.dev.
[Source](https://tour.golang.org/basics/7):
>These names should be used to document the meaning of the return values.
> Name return values for `Screen.Size`

- tscreen.go
A followup to #148 -- currently `NewTerminfoScreenFromTty` still uses local OS environment to get the terminfo and there is no public API to override it.
This PR adds such API, in form of 
- function `NewTerminfoScreenFromTtyTerminfo` that also accepts terminfo instance
- function `LookupTerminfo` that exposes current name-to-terminfo lookup procedure
While `NewTerminfoScreenFromTty` still defeaults to `LookupTerminfo` with $TERM contents to maintain backwards compatability.
> Add API to allow creating Screen using custom terminfo as well as custom tty.

- tscreen.go
**Issue:**
With tcell v2.2.0 and up, mouse events stopped working for PuTTY.  
**Solution:**
When the MouseFlags are not set/present, default the flags to also Include the mouse drag and button events and loop through each mouse event.
**Results w/ fix:**
Mouse events work for PuTTY and other terminals.
> Patch for mouse events not working when using applications from PuTTY terminal 

- views/boxlayout.go
- views/view.go
Constrain viewport visible dimensions to fit within the parent view (`width = min(width,px-x)`).  Currently can overflow (`width > px && width < x+px`) or ignore the requested value (`width > x+px`)
> viewport: truncate size to area avaiable in parent

- _demos/cursors.go
- console_win.go
- screen.go
- simulation.go
- terminfo/mkinfo.go
- terminfo/terminfo.go
- tscreen.go
This adds a new method, SetCursorStyle() to the screen API.
It also automatically restores the cursor when disengaging to
the default cursor.  Modern terminals (and Windows console) support
this.
> fixes #356 Vim cursors shapes?

- terminfo/f/foot/foot.go
There are two “regular”[^1] terminfos for [foot](https://codeberg.org/dnkl/foot). One stripped down version included with ncurses, and another one shipped with foot itself, that contains a number on non-standard capabilities (mainly used by tmux).
Foot’s “own” terminfo is _usually_ packaged as “foot-extra”.
[^1]: there’s actually four; foot also has a “direct” variant (similar to xterm-direct): foot-direct, and foot-extra-direct.
> Add “foot-extra” as a terminfo alias for “foot”

- tscreen.go
Fixed to properly reset enhanced mouse tracking mode (1006) when calling `enableMouse(0)`.
related #477
Behavior before modification:
If I quit the `tcell` application with the mouse enabled and then start `vim`, the cursor doesn't move when I click the mouse.
The symptom was confirmed by `_demos/mouse.go` in the linux environment on Chromebook and Windows.
> enhanced mouse tracking mode (1006) is set improperly when exiting tcell

- go.mod
- go.sum
When using `gdamore/tcell/v2` in the latest release of Go 1.18 we get the following error:
```
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../../go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable …
```
> Upate golang.org/x/sys version to fix bug on darwin with go 1.18

- tscreen.go
In tcell v2.4, the following calls would reset the screen
to its default color:
1. SetContent() to change the bg color to maroon.
2. Clear()
3. Show()
In tcell v2.5, the behavior changed to clear the screen
to the last-used style passed to SetContent.
This happens because commit 62f5502f set the dirty flag
to false for all cells, on the assumption that sending
ti.Clear would clear the cells anyway. Unlike the drawCell
calls triggered by the dirty flag, however, clearScreen
does not send AttrOff. This causes the screen to clear
to the last-used background color.
Issue: https://github.com/gdamore/tcell/issues/522
> Send AttrOff when clearing the screen

- _demos/setsize.go
- console_win.go
- screen.go
- simulation.go
- terminfo/terminfo.go
- tscreen.go
This supports both terminfo (Linux, macOS) terminals, and
the legacy Windows console.  Perversely, the "modern" Windows
terminal doesn't support application initiated resizing yet.
> fixes #462 Console resizing

- views/constants.go
Added the proper type `views.Orientation` for `views.Horizontal` and `views.Vertical` constants.
> Add Horizontal, Vertical const type Orientation (fixes #543)

- README.md
Add a goreportcardbadge so people can see the quality of code used in the project.
> Add goreportcard

- views/view.go
The 'equal to' comparisons in the `ViewPort.ValidateViewX()` and `ViewPort.ValidateViewY()` methods are not required as the `ViewPort`s corresponding `view` attributes will be set equal to the right operand if the conditional resolves as true. The current behaviour results in the `view` attributes being set unnecessarily if it already equals the limit.
> Remove redundant 'equal to' comparison in `ViewPort.ValidateView` methods.

- views/cellarea.go
Fixes #553
This function is supposed to return a minimum 2x2 square. However, as the comparison operators are the wrong way around a maximum 2x2 square is returned instead. Inverting the comparison operators fixes the issue.
> Invert comparison operators in `CellView.Size()`

- style.go
- terminfo/terminfo_test.go
- tscreen.go
OSC8 escape sequences allow for marking up hyperlinks in the terminal. An optional `id` parameter is defined to allow applications to signal to the terminal that (potentially) broken character sequences belong to the same URL and should be treated as if they were connected.
Add support for optional id parameters, set by the application. Update test case for ti.EnterUrl.
Fixes: https://github.com/gdamore/tcell/issues/568
Reference: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#hover-underlining-and-the-id-parameter
> hyperlinks: add support for optional id parameter

- views/app.go
Fixes #552
Identical to https://github.com/gdamore/tcell/commit/c3ed795e59fc3dda826de0fc553e4045bdc2952a, but for pasting.
> Enable paste support in `views.Application`

- style.go
- terminfo/terminfo_test.go
Commit 43efca775e73 added support for url IDs within OSC8 escape sequences, however the formatting of the param is incorrect.
Use `id=` instead of `id:`
Fixes: 43efca775e73 ("hyperlinks: add support for optional id parameter")
> hyperlinks: fix id escape format

- cell.go
ref: https://github.com/jesseduffield/lazygit/issues/1383, https://github.com/jesseduffield/gocui/pull/28#discussion_r1089974893
Fix the afterimage that remains when a cell with wide characters drawn on Windows is overwritten with half-width characters.
run this demo: https://github.com/Ryooooooga/tcell/blob/d29805811f6c0c8ac2846aa8a362437b25e29daf/_demos/hello_world.go
<table>
<tr>
<th>
<th>Windows
<th>mac
<th>Ubuntu (WSL)
<tr>
<th>before
<td>
<td>
<td>
<tr>
<th>after
<td>
<td>
<td>
</table>
> fix wide char rendering on Windows

- console_win.go
The ENABLE_LVB_GRID_WORLDWIDE is needed to enable them.
> Fix underlines in Windows console mode.

- terminfo/dynamic/dynamic.go
Previously, modified function keys in dyanmic terminals were not supported (like shift/control/alt + arrow keys).
Even though xterm-compatible terminals were dynamically discovered and their keys added to the terminfo struct, the Modifiers field was not supported and therefore the modified Xterm keys were not added to the keycodes map (prepareXtermModifiers was skipped).
This fixes the issue by setting the Modifiers field when we discover that the terminal is xterm-compatible.
> Support Xterm modifier keys for dynamic terminfos

- tscreen.go
If a mouse event is a scroll, either up or down, don't set the `buttondn` boolean to true, thereby ensuring buttons are cleared on subsequent mouse movements.
This resolves the issue where scrolling up/down and then moving the mouse causes further `MouseWheel` events.
See issue for more details:
closes #600
> Don't count mouse WheelDown/Up as buttondn

- wscreen.go
This is a workaround for #617.
A better solution would probably be to return a hard-coded Terminfo that matches the Wasm terminal's capabilities, but an unimplemented stub is enough to make [tview](https://github.com/rivo/tview) applications build and run in a browser.
> Add LookupTerminfo stub for wasm

- _demos/sixel.go
- cell.go
- resize.go
- screen.go
- simulation.go
- stdin_unix.go
- tscreen.go
- tty.go
- tty_unix.go
- wscreen.go
Expose underlying TTY and locking mechanism to enable an implementer to directly write to the TTY (if the screen is a terminfo based screen). These two features allow for drawing of sixels on the screen, and locking the cells that are drawn on top of. The locking mechanism enables an implementer to lock tcell's access to drawing to a region of cells. Locks are not transferred during a resize.
Expose the pixel size of the window via EventResize and via a call to tty.WindowSize(). Both methods allow implementers access to the underlying window size in cells and pixels. A helper function is included on the WindowSize struct to calculate the pixel size of a single cell. Pixel sizes are required to calculate the cell size of an image so that an appropriate lock can be obtained.
Add a demo of …
> Direct Drawing to TTY to enable sixel support

- color.go
This is actually to help with handling the base16 colors, to be able to lookup the name of a color to be able to easily pass it into `tview` tag styling which would cause the base16 color schemes to kick in.
Also implemented fmt.Stringer just to get a string rep of a color. Which imo is odd it never has been impl'd.
https://github.com/rivo/tview/issues/859
> implement fmt.Stringer on Color and other string utility methods

- console_win.go
I encountered the following errors when trying to build a Windows binary of [fzf](https://github.com/junegunn/fzf).
```
* cannot use &cScreen{} (value of type *cScreen) as Screen value in return statement: *cScreen does not implement Screen (missing method LockRegion)
* cannot use &cScreen{} (value of type *cScreen) as Screen value in return statement: *cScreen does not implement Screen (missing method Tty)
```
So I just tried to fill in the missing methods by referencing other implementations, but I'm not sure of the correctness as I'm not familiar with the code.
Would it be possible to return a proper value from Tty(), so we can use the "pass-through" mechanism also on Windows? i.e. https://github.com/gdamore/tcell/blob/8a50441ee1fd29b18a4a7d51e98423a17ec8ef4c/_demos/sixel.go#L110-L113 …
> Implement missing methods in cScreen

- console_win.go
AltGr is the same as ctrl+alt, and we don't want those to be set when you press a key using AltGr.
This fixes https://github.com/jesseduffield/lazygit/issues/2839; there, we register keybindings for `[` and `]` without modifiers, but they can't be used with a German keyboard layout, where `[` is typed using AltGr+8. The code that dispatches the keybindings checks that the modifiers are the same; it expects none, but sees ctrl and alt.
Yes, this means it's not possible to register a keybinding for ctrl+[ and have it work for non-US keyboards. But that's no different from, say, `!` on a US keyboard; you can't have a keybinding for shift+! either. (And you don't want to have shift reported as a modifier when typing `!`.)
> Don't set modifiers for AltGr on Windows

- console_win.go
- tscreen.go
This enables the use of VT mode on Windows by default everywhere except ConEmu (because ConEmu is too broken).  The attempt to use (or not use) the vt mode can be controlled by the TCELL_VTMODE environment variable (set it to "enable" or "disable" -- default is enabled unless ConEmu is detected.)
This also uses the alternate screen buffer on Windows by default, with fixes to avoid clearing the non-alternate screen.
It also adds TCELL_ALTSCREEN as an override.  This can be set to "disable" (on either Windows or POSIX), in which case we won't use the alternate screen.  We also don't clear the screen on exit (or disengage) in that case, and the cursor may be at an indeterminate location.  Applications may utilize this to arrange for Tcell to draw the screen, then drop to some other …
> Enhanced Windows VT mode, and ALTSCREEN support

- _demos/stress.go
Small demo that prints different characters, with different formatting, background and frontend.
The frames are pre-generated to render as fast as possible.
Ctrl-C / ESC will quit and print the FPS.
> Add little stresser that just draws as much 'random' stuff as possible

- README.md
Add go-tetris -  a simple tetris game built with tcell.
Works as a native terminal app, have used in Linux and MacOS.
Also works as WASM app. The project is setup to deploy to github pages with github actions build on every commit.
Thanks!
> Add go-tetris

- _demos/cursors.go
- console_win.go
- screen.go
- simulation.go
- terminfo/terminfo.go
- tscreen.go
- webfiles/tcell.js
- webfiles/termstyle.css
- wscreen.go
This adds a new optional parameter to screen.SetCursorStyle, which is a color.  The cursors demo is enhanced to show this.
This ability is supported on screen types, provided the underlying terminal supports the capability.
> fixes #666 cursor color

- _demos/clipboard.go
- console_win.go
- paste.go
- screen.go
- simulation.go
- tscreen.go
This is not supported for Windows or WebAssembly yet. It's possible for applications to post to the clipboard using Screen.SetClipboard (any data), and they can retrieve the clipboard (if permitted) using GetClipboard.  The terminal may well reject either of these.
Retrieval will arrive as a new EventClipboard, if it can.  (There is no good way to make this synchronous.)
This work was inspired by a PR submitted by Consolatis (#562), and has some work based on it, but it was also substantially improved and now includes both sides of the clipboard access pattern.
> fixes #561 Add clipboard support.

- .github/workflows/coverage.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
When running GitHub workflow actions, there are [warnings](https://github.com/gdamore/tcell/actions/runs/8276175862) printed out:
```
Restore cache failed: Dependencies file is not found in /home/runner/work/tcell/tcell.
Supported file pattern: go.sum
```
This PR fixes this issue.
> fix warning 'Restore cache failed'

- terms_dynamic.go
When running in debug mode in VS Code under Linux the Application.Run() method returns an *os/exec.ExitError . This is very confusing and makes tracking down the root cause difficult.
The issue is caused by the default debug environment in VS Code not launching in a terminal.
The error message can be improved by returning an ErrTermNotFound in the case of an empty $TERM environment variable. Hopefully a better error message will lead users to identify the lack of a terminal as the root cause of the problem.
> fixes #716 Improve missing terminal error message.

- attr.go
- cell.go
Adding these length checks before the `reflect.DeepEqual` speeds up SetContent when not drawing Unicode combining characters
With `xset r rate 300 255` (key repeating 255 times per second), I recorded myself scrolling through 2000 files in my file manager project where I'm using [tview](https://github.com/rivo/tview) with and without (left) this change:
https://github.com/user-attachments/assets/9a4f8f83-7a8d-4b5f-b368-8687c53e1ad3
(6x sped up)
I believe the performance difference is a lot less dramatic for most projects, since in this old version of my file manager the screen was always unnecessarily being cleared with [Box.DrawForSubclass()](https://github.com/rivo/tview/blob/b0a7293b81308ab0e44c2757f8922683a3d659df/box.go#L386) in tview
> Speed up SetContent by checking length of combining characters before reflect.DeepEqual

- cell.go
We no longer bother to create the lookup table for runewidth. I had expected this to make a significant difference, but I'm finding that it does not, but it does make the startup time even for applications that only import and never create a screen, considerably worse.  Dozens of milliseconds, even up to half a second.
Applications that need this (persumably some heavy Emoji or EastAsian users) can solve for themselves by importing the runewidth package (same version) and calling the CreateLUT method.
> fixes #764 Adding tcell as a dependency delays startup time

- README.md
- charset_plan9.go
- charset_stub.go
- console_stub.go
- tscreen_plan9.go
- tscreen_stub.go
- tty_plan9.go
This PR introduces **limited Plan 9 support** for `tcell` behind build tags, enabling tcell-based applications (e.g., tview/cview) to compile and run on Plan 9 under `vt(1)` (VT100 emulator). The implementation uses Plan 9’s native console and window-control files to provide raw input, output, and resize notifications, while reusing tcell’s existing **terminfo** screen path.
**Scope:** No behavioral changes on non-Plan9 platforms. Public API is unchanged except for Plan 9–specific implementations.
---
Upstream currently documents Plan 9 as unsupported. This PR provides a clean, low-risk baseline that:
* lets Plan 9 users build and run tcell apps in a console window,
* isolates all Plan 9 code via `//go:build plan9`,
* preserves existing behavior on other platforms.
---
* `tty_plan9.go`
* …
> Adding minimal support for Plan9
