console_win.go, errors.go, event.go, screen.go, sim_test.go, simulation.go, tscreen.go, views/README.md, views/_demos/hbox.go, views/_demos/vbox.go, views/app.go, views/boxlayout.go, views/constants.go, views/spacer.go, views/text.go, views/textbar.go, views/view.go, views/widget.go
fixes #63 Initial views API integration
=> fixes #62 windows console may have FIFO hang

tscreen.go
I think this will take care of all the meta/alt combinations.  Note that this doesn't work for the situation where Alt just toggles the high order bit.  This is a legacy mode that is not recommended, and was used back in the day for Emacs; that mode is incompatible with modern UTF-8 environments.
Please give it a shot.  I hope to merge this soon.  You can test this with the _demo/mouse.go demo
=> fixes #88 Detecting meta/alt key events

README.md
Hi Garrett, please have a look at `godu` and if you think it's a nice example of `tcell` implementation, merge this PR. Cheers
=> Mention godu in Examples section

views/_demos/cellview.go
Some unnecessary code has been removed.
=> cellview: Minor simplifications for the cellview demo

views/cellarea.go, views/textarea.go
Please see the commit messages.
=> small improvements to the views package

simulation.go
So that we can test for special key sequences. Fixes #198.
=> Fix InjectKey of simscreen

console_win.go
Fixes https://github.com/gdamore/tcell/issues/205
=> convert shift+tab to backtab

encoding/all.go
I know, most useful PR of the year award right here
=> docs typo encoodings -> encodings

README.md
Add browsh to the list of examples.
=> Update README.md / Add browsh to examples

README.md
Thank you for your great work!
I developed small app by using tcell.
https://github.com/sachaos/go-life
If you like this, please merge this PR.
=> Update README.md / Add go-life to examples

README.adoc
Hi - the two linked projects depend completely on tcell! If you see fit, and if it would help advertise tcell just a little more, would you add these links to your README?
Graham
=> Shamelessly add my two tcell projects to the README ;-)

README.adoc
Gitter usability is decreasing; discord looks better these days.
=> Add link to discord server

views/textarea.go
This makes working with multibyte characters much easier, as you do not have to count bytes from line beginning.
It also fixes hungarian accent characters for me, should fix other single with accents too, but Chinese chars probably still need some love.
=> TextArea: use [][]rune instead of []string in linesModel

views/textarea.go, views/textarea_test.go
I have messed up this with my latest PR, but did not notice before. Sorry.
=> Fix TextArea SetContent method

README.adoc
=> Add cbind to examples

_demos/hello_world.go
When I was trying to get started with tcell, I found the provided demos a little intimidating. Thus I created the most minimal demo I could think of. Might also help with https://github.com/gdamore/tcell/issues/163#issuecomment-603932645.
=> Add "Hello, World!" demo

console_win.go
This seems to work well on conemu, but doesn't work at all normally
in the stock Windows 10 console.  However, if you run under env, it
will 'sort of work', meaning once you press enter things seem to work.
This is for experimentation, opt-in only.  To enable this, set the
environment variable TCELL_TRUECOLOR to "enable".
Advice to fix this for console hosts is requested.
=> Initial swag at 24-bit color support for Windows consoles.

terminfo/models.txt
Otherwise, deleting all `term.go` and re-running `bash gen.sh` does _not_ produce everything again.
=> Add missing entries to models.txt.

style.go
PR as requested in rivo/tview#506.
I also fixed some comments. I hope that's ok.
=> Added a function to Style that sets its attributes.

README.adoc
Hopefully worthy of being in this list. termbox-go has similar touch-typing tutor in its examples, maybe tcell should too.
=> Add another example project

TUTORIAL.adoc
=> Add tutorial

README.adoc
Added my small project, called 'gonano', that uses tcell.
=> Added example project that uses tcell

README.adoc
Adding another tcell project as requested.
=> Added example project uchess

README.adoc
How about another example repo?
=> Add https://github.com/a-h/min to the examples

README.adoc
Please add it to examples if you like. This is the terminal pager I made.
=> Added terminal pager ov to examples

README.md
These are just some tools I threw together for personal use which leverage tcell.  I thought you'd like to have them included, but they are very new so no worries if they are not mature enough to be included on this list.
=> Adding some small tcell repos I threw together

views/app.go
After writing up https://github.com/gdamore/tcell/issues/493 I pulled the `app.go` file directly into my project and added the `screen.EnableMouse()` line... ended up working fine 🙂 
Admittedly though I'm not very familiar with this library. Are there caveats to enabling mouse support here - either with regards to errors or with functionality in the views module widgets?
=> Enable mouse support in views.Application

README.md
Please add the application example I developed by using your library.
=> Add examples in README.md

paste.go
Just a very minor one that I stumbled over.
=> Fix doc typo

views/widget.go
The WidgetWatchers struct is designed to be embedded into custom widgets in order to satisfy the WidgetWatcher interface. The implementation uses an internal map for storing EventHandlers, but does not lock access to the access of the map within each method. A race condition can occur if Watch, Unwatch, or any event is Posted from separate goroutines.
Lock access to the internal map. When posting an event, create a deep copy of the map for iterating. This prevents potential deadlocks from a widget calling Unwatch while handling an event.
=> widgets: lock access to WidgetWatchers internal map

README.md
Update the README with the link of an another example of use of tcell.
=> update README with gbb repo link

README.md
Thank you for your wonderful library!
=> Add a new examples repo based on tcell to readme

README.md
I added my example project to the readme with video
=> Readme updated, an example project [hero.go] added

tscreen.go
=> fix: horizontal scroll events were not emitted

style.go
=> Add public methods for UnderlineStyle and UnderlineColor
